### ISSUE TITLE
Provide a system for distributing required DLL's to build editor

### ISSUE THREAD

**Issue by JDSherbert** [JDSherbert/Sherbert-Engine#11]

**Comment by VerzatileDev** [comment]
Issue
---
I believe it is referring to "build events" in the context of including specified DLLs from one location to another, essential for the proper functioning of the program.

Proposal
---
I've tackled the DLL inclusion during build events and it might be of good use to solve the current issue. The solution on [VS.DLLinFolder](https://github.com/VerzatileDevOrg/VS.DLLinFolder). Outlines how to handle "System," "Local Directory," and "Online DLLs" during pre-link events, eliminating the manual steps required for each build.

Solves
---
This would solve the problem of adding the following manual each time a build is made https://github.com/JDSherbert/Sherbert-Engine/commit/e4e802d27ba275324f70d14a4dfdcfe6df812686 .

Additionally the same could be used to specify required folders such as https://github.com/JDSherbert/Sherbert-Engine/issues/8 if and when they must be in a specified directory when

**Comment by VerzatileDev** [comment]
> nice, that's a good idea. I'll take a look into at some point.

I don't mind adding it to a pull request with the additional steps you can change or take depending on the use-case.
To get a better overall picture of it

**Comment by VerzatileDev** [comment]
Issue addressed in PR : https://github.com/JDSherbert/Sherbert-Engine/pull/24 

- Closes issue
