### ISSUE TITLE
Address " non-Compile " IMGUI Default Path

### ISSUE THREAD

**Issue by VerzatileDev** [JDSherbert/Sherbert-Engine#38]
Issue
---

https://github.com/JDSherbert/Sherbert-Engine/commit/7bb7031d151d85422a4128a3576b3f8e992b4892 

IMGUI config directory, and default path change incorrectly done and produces a non-compile.

Solution
---

Address the previous changes and modify them to work as intended

Solves
---

https://github.com/JDSherbert/Sherbert-Engine/pull/37  That was no completed

Issue listed here https://github.com/JDSherbert/Sherbert-Engine/commit/7bb7031d151d85422a4128a3576b3f8e992b4892

**Comment by JDSherbert** [comment]
resolved
